# **crosstab**
- 범주형 데이터를 비교분석할 때 유용합니다.
- `pd.crosstab(index=행, columns=열, margins=True/False, normalize=True/False)`

---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd

file_path = r'./data/titanic_train.csv'
df = pd.read_csv(file_path)

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **범주별 갯수 구하기**
- `pd.crosstab(행, 열)`

In [ ]:
pd.crosstab(df['Sex'], df['Survived'])  ## 성별이 여자, 남자에 따라 생존율이 어떻게 달라지는지 확인

Survived    0    1
Sex
female     81  233
male      468  109

In [ ]:
pd.crosstab(df['Pclass'], df['Survived']) ## Pclass에 따라 생존율이 어떻게 달라지는지 확인

Survived    0    1
Pclass
1          80  136
2          97   87
3         372  119

## **범주별 비율 구하기**
- `normalize = 'all'`: 전체 합이 100%
- `normalize = 'index'`: 행별 합이 100%
- `normalize = 'columns'`: 열별 합이 100%

In [ ]:
pd.crosstab(df['Sex'], df['Survived'], normalize='all')  ## 전체를 기준으로 각각의 생존율을 확인

Survived         0         1
Sex
female    0.090909  0.261504
male      0.525253  0.122334

In [ ]:
pd.crosstab(df['Sex'], df['Survived'], normalize='index')  ## 행별로 100% 계산. 여자 중에서 생존율, 남자 중에서 생존율을 확인

Survived         0         1
Sex
female    0.257962  0.742038
male      0.811092  0.188908

In [ ]:
pd.crosstab(df['Sex'], df['Survived'], normalize='columns') ## 열별로 100% 계산. 생존자, 사망자 중에서 여자, 남자 비율을 확인

Survived         0         1
Sex
female    0.147541  0.681287
male      0.852459  0.318713

In [ ]:
pd.crosstab(df['Sex'], df['Survived'], normalize='all', margins=True)  ## 행과 열의 합계를 추가하여 전체 비율을 확인. 전체를 100으로 보았다

Survived         0         1       All
Sex
female    0.090909  0.261504  0.352413
male      0.525253  0.122334  0.647587
All       0.616162  0.383838  1.000000

In [ ]:
pd.crosstab(df['Sex'], df['Survived'], normalize='index', margins=True)  
## 행이 100% 기준으로 계산. 전체 여자 중에서 생존율, 남자 중에서 생존율을 확인. 전체 성별 중에서의 비율도 확인 가능

Survived         0         1
Sex
female    0.257962  0.742038
male      0.811092  0.188908
All       0.616162  0.383838

In [ ]:
pd.crosstab(df['Sex'], df['Survived'], normalize='columns', margins=True)
## 열이 100% 기준으로 계산. 전체 생존자, 사망자 중에서 여자, 남자 비율을 확인.

## **다중 인덱스, 다중 컬럼의 범주표 구하기**

In [11]:
pd.crosstab(index=[df['Sex'], df['Pclass']], columns=df['Survived'])

Survived         0   1
Sex    Pclass
female 1         3  91
       2         6  70
       3        72  72
male   1        77  45
       2        91  17
       3       300  47

In [ ]:
pd.crosstab(index=[df['Sex'], df['Pclass']], columns=df['Survived'], normalize='all')
## 전체를 100% 기준으로 계산. 성별과 Pclass에 따라 생존율을 확인

Survived              0         1
Sex    Pclass
female 1       0.003367  0.102132
       2       0.006734  0.078563
       3       0.080808  0.080808
male   1       0.086420  0.050505
       2       0.102132  0.019080
       3       0.336700  0.052750

In [13]:
pd.crosstab(index=[df['Sex'], df['Pclass']], columns=df['Survived'], normalize='columns')
## 열이 100% 기준으로 계산. 생존자, 사망자 중에서 성별과 Pclass에 따라 비율을 확인

Survived              0         1
Sex    Pclass
female 1       0.005464  0.266082
       2       0.010929  0.204678
       3       0.131148  0.210526
male   1       0.140255  0.131579
       2       0.165756  0.049708
       3       0.546448  0.137427

In [ ]:
pd.crosstab(index=[df['Sex'], df['Pclass']], columns=[df['Survived'], df['Embarked']])
## 컬럼에 여러개 넣기(리스트로 표현). 성별과 Pclass에 따라 생존자, 사망자와 탑승 항구에 따른 비율을 확인.

Survived        0            1
Embarked        C   Q    S   C   Q   S
Sex    Pclass
female 1        1   0    2  42   1  46
       2        0   0    6   7   2  61
       3        8   9   55  15  24  33
male   1       25   1   51  17   0  28
       2        8   1   82   2   0  15
       3       33  36  231  10   3  34

In [ ]:
pd.crosstab(index=[df['Sex'], df['Pclass']], columns=[df['Survived'], df['Embarked']], normalize='all')
## 전체를 100% 기준으로 계산. 성별과 Pclass에 따라 생존율과 탑승 항구에 따른 비율을 확인

Survived              0                             1
Embarked              C         Q         S         C         Q         S
Sex    Pclass
female 1       0.001125  0.000000  0.002250  0.047244  0.001125  0.051744
       2       0.000000  0.000000  0.006749  0.007874  0.002250  0.068616
       3       0.008999  0.010124  0.061867  0.016873  0.026997  0.037120
male   1       0.028121  0.001125  0.057368  0.019123  0.000000  0.031496
       2       0.008999  0.001125  0.092238  0.002250  0.000000  0.016873
       3       0.037120  0.040495  0.259843  0.011249  0.003375  0.038245