# **folium으로 지리 데이터 시각화하기**


---
서울시의 이디야, 투썸플레이스 위치를 시각화하고 두 카페의 지리적 분포가 어떻게 다른지 시각화를 통해 살펴봅시다.

In [1]:
import json
import folium
import pandas as pd

## **[1] 서울시 구별 경계 데이터 가져오기**

- [서울시 구별 경계 데이터](https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo.json)

In [2]:
geo_path = r"C:\Users\ryang\OneDrive\문서\공부\part.2\data\seoul_municipalities_geo_simple.json"
geo_json = json.load(open(geo_path, encoding='utf-8'))

In [9]:
geo_json

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'properties': {'code': '11250',
    'name': '강동구',
    'name_eng': 'Gangdong-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.11519584981606, 37.557533180704915],
      [127.11879551821994, 37.557222485451305],
      [127.12146867175024, 37.55986003393365],
      [127.12435254630417, 37.56144246249796],
      [127.13593925898998, 37.56564793048277],
      [127.14930548011061, 37.56892250303897],
      [127.15511020940411, 37.57093642128295],
      [127.16683184366129, 37.57672487388627],
      [127.17038810813094, 37.576465605301046],
      [127.17607118428914, 37.57678573961056],
      [127.17905504160184, 37.57791388161732],
      [127.17747787800164, 37.57448983055031],
      [127.1781775408844, 37.571481967974336],
      [127.17995281860672, 37.569309661290504],
      [127.18122821955262, 37.56636089217979],
      [127.18169407550688, 37.56286338914073],
      [127.18408792330152, 37.55814280369575],
      [127.18350810324185, 37.550053002101485],
      [127.1852644795464, 37.54888592026534],
      [127.18480906237207, 37.545296888806796],
      [127.18543378919821, 37.54260756512178],
      [127.18364810569703, 37.54241347907019],
      [127.18116465939269, 37.54384126582126],
      [127.17770860504257, 37.542414255164374],
      [127.1744373170213, 37.54277723796397],
      [127.16830424484573, 37.54145405702079],
      [127.16530984307447, 37.54221851258693],
      [127.15566835118616, 37.53119520531309],
      [127.15538075046105, 37.52652930087977],
      [127.15154315998161, 37.522828709496416],
      [127.14981542759394, 37.51926843453025],
      [127.14791518058246, 37.51918714979303],
      [127.14684644251928, 37.51661384818575],
      [127.14672806823502, 37.51415680680291],
      [127.14532023498624, 37.51464060108829],
      [127.12123165719615, 37.52528270089],
      [127.12251496040881, 37.52751810228347],
      [127.12532464331997, 37.53572787912298],
      [127.12061313033807, 37.538129867839416],
      [127.1116764203608, 37.540669955324965],
      [127.11418412219375, 37.54474592090681],
      [127.11600200349189, 37.55053147511706],
      [127.11600943681239, 37.55580061507081],
      [127.11519584981606, 37.557533180704915]]]}},
  {'type': 'Feature',
   'properties': {'code': '11240',
    'name': '송파구',
    'name_eng': 'Songpa-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.0690698130372, 37.522279423505026],
      [127.07496309841329, 37.52091052765938],
      [127.07968915919895, 37.52077294752823],
      [127.08639455667742, 37.52161824624356],
      [127.0943611414465, 37.523984206117525],
      [127.10087519791962, 37.524841220167055],
      [127.10484130265957, 37.53120327509912],
      [127.1116764203608, 37.540669955324965],
      [127.12061313033807, 37.538129867839416],
      [127.12532464331997, 37.53572787912298],
      [127.12251496040881, 37.52751810228347],
      [127.12123165719615, 37.52528270089],
      [127.14532023498624, 37.51464060108829],
      [127.14672806823502, 37.51415680680291],
      [127.14670263739373, 37.512786602955565],
      [127.14462782318448, 37.511529542030715],
      [127.14323992504048, 37.50951977457089],
      [127.1420864475393, 37.50578973782813],
      [127.14324986168657, 37.502649431479774],
      [127.1473517108062, 37.50069754405746],
      [127.14980119646964, 37.50046502392898],
      [127.15223804785649, 37.50170492532197],
      [127.15401160147654, 37.500347919909956],
      [127.16086308579277, 37.49886565522751],
      [127.1634944215765, 37.497445406097484],
      [127.16199885180917, 37.49402577547199],
      [127.16216448592424, 37.491639601211624],
      [127.16040295326431, 37.4877818619403],
      [127.15892216655034, 37.486126922469445],
      [127.15393282790794, 37.48483891408459],
      [127.15147990997852, 37.47745324805034],
      [127.1515017465549, 37.475633269417585],
      [127.14857580353349, 37.47381386382568],
      [127.14415938171436, 37.473692508393505],
      [127.14112111404233, 37.470600239054825],
      [127.13631568648837, 37.47214721764681],
      [127.13281577200672, 37.47257463763244],
      [127.13307493070646, 37.468907694139894],
      [127.13750907701846, 37.46647058226059],
      [127.13478085797742, 37.46509524639883],
      [127.1308437061496, 37.46509985661207],
      [127.12728991002369, 37.46673043118672],
      [127.12729757787379, 37.46421548908766],
      [127.12440571080893, 37.46240445587048],
      [127.12441393026374, 37.46442715236855],
      [127.12265007208167, 37.46756987490939],
      [127.11380709617507, 37.479633334849325],
      [127.1143875173445, 37.48073157362458],
      [127.11117085201238, 37.485708381512445],
      [127.1077937689776, 37.48860875954992],
      [127.10433125798602, 37.490728250649646],
      [127.0988509639092, 37.49302529254068],
      [127.08050206733888, 37.49783151325589],
      [127.0764808967127, 37.498612695580306],
      [127.0719146000724, 37.50224013587669],
      [127.06926628842805, 37.51717796437217],
      [127.06860425556381, 37.51812758676938],
      [127.0690698130372, 37.522279423505026]]]}},
  {'type': 'Feature',
   'properties': {'code': '11230',
    'name': '강남구',
    'name_eng': 'Gangnam-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.05867359288398, 37.52629974922568],
      [127.0690698130372, 37.522279423505026],
      [127.06860425556381, 37.51812758676938],
      [127.06926628842805, 37.51717796437217],
      [127.0719146000724, 37.50224013587669],
      [127.0764808967127, 37.498612695580306],
      [127.08050206733888, 37.49783151325589],
      [127.0988509639092, 37.49302529254068],
      [127.10433125798602, 37.490728250649646],
      [127.1077937689776, 37.48860875954992],
      [127.11117085201238, 37.485708381512445],
      [127.1143875173445, 37.48073157362458],
      [127.11380709617507, 37.479633334849325],
      [127.12265007208167, 37.46756987490939],
      [127.12441393026374, 37.46442715236855],
      [127.12440571080893, 37.46240445587048],
      [127.11957248720776, 37.45936217377656],
      [127.11885903757606, 37.45578434878651],
      [127.11535741803938, 37.45722556454321],
      [127.11413179478714, 37.45875072431525],
      [127.10841788934951, 37.45972888008147],
      [127.10561257180657, 37.456815702518746],
      [127.10032466845217, 37.45598440195682],
      [127.09842759318751, 37.45862253857461],
      [127.09712653145507, 37.460848194480654],
      [127.09039613625872, 37.465520545397716],
      [127.0866005634691, 37.47006403057779],
      [127.08640440578156, 37.472697935184655],
      [127.0802737559454, 37.471973057552624],
      [127.07602132306535, 37.47005021331707],
      [127.07476117209941, 37.47199174520626],
      [127.07231320371885, 37.47234914588019],
      [127.07135137525977, 37.47107802023145],
      [127.06463901956462, 37.47003474490574],
      [127.06371868919344, 37.4661503234869],
      [127.0588551029968, 37.465611780743174],
      [127.0559170481904, 37.4659228914077],
      [127.04713549385288, 37.474479419244865],
      [127.04345123620755, 37.48276415595109],
      [127.03621915098798, 37.48175802427603],
      [127.03372275812187, 37.48674434662411],
      [127.02265609299096, 37.509970106251416],
      [127.02038705349842, 37.51771683027875],
      [127.01917707838057, 37.520085205855196],
      [127.01397119667513, 37.52503988289669],
      [127.02302831890559, 37.53231899582663],
      [127.0269608080842, 37.53484752757724],
      [127.0319617044248, 37.536064291470424],
      [127.04806779588436, 37.52970198575087],
      [127.04903802830752, 37.53140496708317],
      [127.05116490008963, 37.52975116557232],
      [127.05867359288398, 37.52629974922568]]]}},
  {'type': 'Feature',
   'properties': {'code': '11220',
    'name': '서초구',
    'name_eng': 'Seocho-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[127.01397119667513, 37.52503988289669],
      [127.01917707838057, 37.520085205855196],
      [127.02038705349842, 37.51771683027875],
      [127.02265609299096, 37.509970106251416],
      [127.03372275812187, 37.48674434662411],
      [127.03621915098798, 37.48175802427603],
      [127.04345123620755, 37.48276415595109],
      [127.04713549385288, 37.474479419244865],
      [127.0559170481904, 37.4659228914077],
      [127.0588551029968, 37.465611780743174],
      [127.06371868919344, 37.4661503234869],
      [127.06463901956462, 37.47003474490574],
      [127.07135137525977, 37.47107802023145],
      [127.07231320371885, 37.47234914588019],
      [127.07476117209941, 37.47199174520626],
      [127.07602132306535, 37.47005021331707],
      [127.0802737559454, 37.471973057552624],
      [127.08640440578156, 37.472697935184655],
      [127.0866005634691, 37.47006403057779],
      [127.09039613625872, 37.465520545397716],
      [127.09712653145507, 37.460848194480654],
      [127.09842759318751, 37.45862253857461],
      [127.09673714758375, 37.45597209899094],
      [127.09722129576434, 37.45374822681991],
      [127.09575982122928, 37.45332980525459],
      [127.09472136159357, 37.450897902539175],
      [127.09293250684935, 37.450020696864506],
      [127.09047890749349, 37.44637473407341],
      [127.09046928565951, 37.44296826114185],
      [127.0862358725955, 37.44118543250345],
      [127.08441983692467, 37.4383879031398],
      [127.07686576585408, 37.43960712011444],
      [127.07375875606847, 37.43898415920535],
      [127.07407631675713, 37.43719357187124],
      [127.07666569012467, 37.43600054505559],
      [127.07603719210388, 37.43429107517633],
      [127.07361291761038, 37.43318474533595],
      [127.07271473569163, 37.42939553659177],
      [127.0733788318578, 37.42814484786288],
      [127.06885354151605, 37.42731815367302],
      [127.06778107605433, 37.426197424057314],
      [127.06317558623768, 37.4272916178182],
      [127.05998777565219, 37.4273224867045],
      [127.05424556064274, 37.42574929824175],
      [127.05197080928994, 37.42749842502397],
      [127.04960937636815, 37.42801020057224],
      [127.04849622718511, 37.430672016902065],
      [127.04191594772718, 37.43568906449929],
      [127.0379686253535, 37.43634417139204],
      [127.03751805596916, 37.438362795245276],
      [127.04031700689708, 37.44191429311459],
      [127.03959875976469, 37.443582700519194],
      [127.0398984887873, 37.44656106007936],
      [127.03825522385397, 37.448766467898395],
      [127.03916301678915, 37.45180237055558],
      [127.03881782597922, 37.45382039851715],
      [127.03695436044305, 37.45537592726508],
      [127.03573307034355, 37.4586703897792],
      [127.03683946894893, 37.46103886642786],
      [127.03337331972266, 37.462966775127626],
      [127.02820831539744, 37.455700834295826],
      [127.02263694708293, 37.45335816711404],
      [127.01827371395349, 37.4525593623189],
      [127.01316256500736, 37.45257906566242],
      [127.01110931353561, 37.45456166745922],
      [127.00836380369604, 37.45936868039916],
      [127.00738548779366, 37.459815333664274],
      [127.00552362663117, 37.46445102893571],
      [127.00008523087483, 37.46455774995882],
      [126.99837609897334, 37.46390918086617],
      [126.99932142462428, 37.46113351815481],
      [126.99893310307874, 37.459376062410314],
      [126.9953054179472, 37.45860121328987],
      [126.99072073195462, 37.455326143310025],
      [126.98956736277059, 37.457600756400446],
      [126.99026416700147, 37.46271603227842],
      [126.98896316546526, 37.465041871263544],
      [126.98662755598336, 37.466937278295305],
      [126.9846374349825, 37.46996301876212],
      [126.98367668291802, 37.473856492692086],
      [126.98500224966135, 37.49356837311327],
      [126.9871787157338, 37.49719505997539],
      [126.9832495184969, 37.49948552591205],
      [126.98241580381733, 37.50120029501884],
      [126.98223807916081, 37.509314966770326],
      [126.98458580602838, 37.51070333105394],
      [126.98948242685965, 37.5108780134613],
      [126.99148001917875, 37.50990503427709],
      [127.00011962020382, 37.513901653034374],
      [127.00583392114271, 37.516905128452926],
      [127.00818058911564, 37.51877313923874],
      [127.01022186960886, 37.522020085671926],
      [127.01397119667513, 37.52503988289669]]]}},
  {'type': 'Feature',
   'properties': {'code': '11210',
    'name': '관악구',
    'name_eng': 'Gwanak-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[126.98367668291802, 37.473856492692086],
      [126.9846374349825, 37.46996301876212],
      [126.98662755598336, 37.466937278295305],
      [126.98896316546526, 37.465041871263544],
      [126.99026416700147, 37.46271603227842],
      [126.98956736277059, 37.457600756400446],
      [126.99072073195462, 37.455326143310025],
      [126.98484249930785, 37.45391909788938],
      [126.9829408096241, 37.450206782833206],
      [126.97835022660695, 37.447659155806164],
      [126.97608193440507, 37.44478918862847],
      [126.9731300196836, 37.444722870088114],
      [126.96650852936277, 37.44276983031553],
      [126.96618702895445, 37.439376482995094],
      [126.96520439085143, 37.438249784006246],
      [126.9614877541633, 37.437956805629675],
      [126.96054904645496, 37.43673997185797],
      [126.95527369898224, 37.43673711968809],
      [126.9473688393239, 37.4347689647565],
      [126.94440352544498, 37.43476162120059],
      [126.9415292183489, 37.43315139671158],
      [126.94037501670272, 37.43462213966344],
      [126.9405640311191, 37.437501011208845],
      [126.9376981355065, 37.44041709605302],
      [126.93312955918624, 37.44290014710262],
      [126.93309127096236, 37.44533734785938],
      [126.93084408056525, 37.447382928333994],
      [126.92527839995981, 37.45161884570837],
      [126.9245243450059, 37.45392293573877],
      [126.91887928082078, 37.45495082787016],
      [126.9167728146601, 37.45490566423789],
      [126.91641538472182, 37.45870245071989],
      [126.91495285904284, 37.461166184511065],
      [126.91584245173756, 37.462474576247985],
      [126.91374656127704, 37.46375990852858],
      [126.91032166997253, 37.469818629944285],
      [126.91280966667205, 37.47083063715413],
      [126.91405961426707, 37.47416764846582],
      [126.9115784808617, 37.4753960485947],
      [126.91181700249076, 37.47814319736339],
      [126.90276666415615, 37.47652007992712],
      [126.90156094129895, 37.47753842789901],
      [126.90531975801812, 37.48218087575429],
      [126.90805655355825, 37.48218338568103],
      [126.91533979779165, 37.484392208242134],
      [126.91916807529428, 37.48660606817164],
      [126.92639563063156, 37.48715979752876],
      [126.92869559665061, 37.49132126714011],
      [126.92981699800066, 37.49218420958284],
      [126.93346386636452, 37.49043826776755],
      [126.93669800083833, 37.49026778789087],
      [126.93844070234584, 37.4893532861132],
      [126.94373156012337, 37.48938843727846],
      [126.94922661389508, 37.49125437495649],
      [126.95396955055433, 37.48955250290043],
      [126.9559655046206, 37.48820165625994],
      [126.95881175306481, 37.48874989165474],
      [126.96329694970828, 37.4905835370787],
      [126.96291787066104, 37.48803272157808],
      [126.96443983219191, 37.48442261322104],
      [126.9634428120456, 37.48067931902171],
      [126.9725891850662, 37.472561363278125],
      [126.97901795539295, 37.47376525108475],
      [126.98367668291802, 37.473856492692086]]]}},
  {'type': 'Feature',
   'properties': {'code': '11200',
    'name': '동작구',
    'name_eng': 'Dongjak-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[126.98223807916081, 37.509314966770326],
      [126.98241580381733, 37.50120029501884],
      [126.9832495184969, 37.49948552591205],
      [126.9871787157338, 37.49719505997539],
      [126.98500224966135, 37.49356837311327],
      [126.98367668291802, 37.473856492692086],
      [126.97901795539295, 37.47376525108475],
      [126.9725891850662, 37.472561363278125],
      [126.9634428120456, 37.48067931902171],
      [126.96443983219191, 37.48442261322104],
      [126.96291787066104, 37.48803272157808],
      [126.96329694970828, 37.4905835370787],
      [126.95881175306481, 37.48874989165474],
      [126.9559655046206, 37.48820165625994],
      [126.95396955055433, 37.48955250290043],
      [126.94922661389508, 37.49125437495649],
      [126.94373156012337, 37.48938843727846],
      [126.93844070234584, 37.4893532861132],
      [126.93669800083833, 37.49026778789087],
      [126.93346386636452, 37.49043826776755],
      [126.92981699800066, 37.49218420958284],
      [126.92869559665061, 37.49132126714011],
      [126.92639563063156, 37.48715979752876],
      [126.91916807529428, 37.48660606817164],
      [126.91533979779165, 37.484392208242134],
      [126.90805655355825, 37.48218338568103],
      [126.90531975801812, 37.48218087575429],
      [126.91461888105147, 37.493581242537296],
      [126.92177893174825, 37.494889877415176],
      [126.9232469824303, 37.49928149943772],
      [126.92749463764046, 37.50985955934051],
      [126.92919938332032, 37.51019685838638],
      [126.92810628828279, 37.51329595732015],
      [126.93453120783802, 37.5128512712934],
      [126.94407346439685, 37.51463101265907],
      [126.95249990298159, 37.51722500741813],
      [126.95551848909955, 37.514736123015844],
      [126.95950268374823, 37.51249532165974],
      [126.96670111119346, 37.50997579058433],
      [126.98223807916081, 37.509314966770326]]]}},
  {'type': 'Feature',
   'properties': {'code': '11190',
    'name': '영등포구',
    'name_eng': 'Yeongdeungpo-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[126.89184663862764, 37.547373974997114],
      [126.90281125423546, 37.54133630026083],
      [126.90829204147958, 37.539206065016785],
      [126.93132557924062, 37.53415416375281],
      [126.93680342222562, 37.53344577095931],
      [126.94566733083212, 37.526617542453366],
      [126.9488066464266, 37.52424913252661],
      [126.95003825019774, 37.520781022055274],
      [126.95249990298159, 37.51722500741813],
      [126.94407346439685, 37.51463101265907],
      [126.93453120783802, 37.5128512712934],
      [126.92810628828279, 37.51329595732015],
      [126.92919938332032, 37.51019685838638],
      [126.92749463764046, 37.50985955934051],
      [126.9232469824303, 37.49928149943772],
      [126.92177893174825, 37.494889877415176],
      [126.91461888105147, 37.493581242537296],
      [126.90531975801812, 37.48218087575429],
      [126.90260188508027, 37.48282626920736],
      [126.89861362258316, 37.48625405368759],
      [126.89581061458084, 37.49391346191318],
      [126.89549571721683, 37.50033127915717],
      [126.89594776782485, 37.504675281309176],
      [126.89253696873205, 37.50875582175844],
      [126.88156402353862, 37.513970034765684],
      [126.88191372979959, 37.51939416754389],
      [126.88260109180834, 37.52242565920786],
      [126.88382776477316, 37.52352483439659],
      [126.88904768965743, 37.525856504359034],
      [126.89057378109133, 37.52792091672938],
      [126.89213569003026, 37.52757969298779],
      [126.89361739665432, 37.53033899535983],
      [126.89339176028666, 37.533030814524004],
      [126.88938421776182, 37.54060159145325],
      [126.88825757860099, 37.54079733630232],
      [126.88736718003831, 37.54350482420959],
      [126.89184663862764, 37.547373974997114]]]}},
  {'type': 'Feature',
   'properties': {'code': '11180',
    'name': '금천구',
    'name_eng': 'Geumcheon-gu',
    'base_year': '2013'},
   'geometry': {'type': 'Polygon',
    'coordinates': [[[126.90156094129895, 37.47753842789901],
      [126.90276666415615, 37.47652007992712],
      [126.91181700249076, 37.47814319736339],
      [126.9115784808617, 37.4753960485947],

## **[2] 서울시 상가 정보 데이터 가져오기**
- [공공데이터포털](https://www.data.go.kr/data/15083033/fileData.do)

In [14]:
df = pd.read_csv(r"C:\Users\ryang\OneDrive\문서\공부\part.2\data\소상공인시장진흥공단_상가(상권)정보_서울_202306.csv", low_memory=False)

In [16]:
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0037544,영자's곱창,NaN,I2,음식,I201,한식,I20109,곱창 전골/구이,I56111,한식 일반 음식점업,11,서울특별시,11215,광진구,11215760,중곡3동,1121510100,중곡동,1121510100101690021,1,대지,169,21.0,서울특별시 광진구 중곡동 169-21,112153005027,서울특별시 광진구 면목로,172.0,NaN,1121510100101690021003140,NaN,서울특별시 광진구 면목로 172,143900,4904,NaN,1,NaN,127.082832,37.568503
1,MA0101202210A0097916,호텔클로이,NaN,I1,숙박,I101,일반 숙박,I10102,여관/모텔,I55102,여관업,11,서울특별시,11140,중구,11140590,광희동,1114014500,광희동1가,1114014500101300000,1,대지,130,NaN,서울특별시 중구 광희동1가 130,111404103258,서울특별시 중구 을지로42길,11.0,NaN,1114014500101300000014092,유성장,서울특별시 중구 을지로42길 11,100411,4561,NaN,NaN,NaN,127.005849,37.565708
2,MA0101202210A0096343,나라차중계태권도장,NaN,P1,교육,P106,기타 교육,P10601,태권도/무술학원,P85611,태권도 및 무술 교육기관,11,서울특별시,11350,노원구,11350619,중계본동,1135010600,중계동,1135010600103640019,1,대지,364,19.0,서울특별시 노원구 중계동 364-19,113503110009,서울특별시 노원구 한글비석로,242.0,NaN,1135010600103640019010971,삼부프라자,서울특별시 노원구 한글비석로 242,139861,1734,NaN,NaN,NaN,127.076956,37.649226
3,MA0101202210A0093845,이상한스냅,NaN,M1,과학·기술,M113,사진 촬영,M11301,사진촬영업,M73303,사진 처리업,11,서울특별시,11470,양천구,11470600,신월5동,1147010300,신월동,1147010300100090004,1,대지,9,4.0,서울특별시 양천구 신월동 9-4,114703005067,서울특별시 양천구 월정로,283.0,NaN,1147010300100090004000001,백송주택,서울특별시 양천구 월정로 283,158822,7902,NaN,NaN,NaN,126.828832,37.542117
4,MA010120220805430767,토끼정,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,한식 일반 음식점업,11,서울특별시,11500,강서구,11500603,가양1동,1150010500,마곡동,1150010500107740012,1,대지,774,12.0,서울특별시 강서구 마곡동 774-12,115003155046,서울특별시 강서구 마곡동로,55.0,NaN,1150010500107740012000001,마커스빌딩,서울특별시 강서구 마곡동로 55,157805,7802,NaN,2,NaN,126.833022,37.560053

In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)  # 모든 열 보기
pd.set_option('display.width', None)        # 줄바꿈 없이 출력

display(df.head())

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0037544,영자's곱창,NaN,I2,음식,I201,한식,I20109,곱창 전골/구이,I56111,한식 일반 음식점업,11,서울특별시,11215,광진구,11215760,중곡3동,1121510100,중곡동,1121510100101690021,1,대지,169,21.0,서울특별시 광진구 중곡동 169-21,112153005027,서울특별시 광진구 면목로,172.0,NaN,1121510100101690021003140,NaN,서울특별시 광진구 면목로 172,143900,4904,NaN,1,NaN,127.082832,37.568503
1,MA0101202210A0097916,호텔클로이,NaN,I1,숙박,I101,일반 숙박,I10102,여관/모텔,I55102,여관업,11,서울특별시,11140,중구,11140590,광희동,1114014500,광희동1가,1114014500101300000,1,대지,130,NaN,서울특별시 중구 광희동1가 130,111404103258,서울특별시 중구 을지로42길,11.0,NaN,1114014500101300000014092,유성장,서울특별시 중구 을지로42길 11,100411,4561,NaN,NaN,NaN,127.005849,37.565708
2,MA0101202210A0096343,나라차중계태권도장,NaN,P1,교육,P106,기타 교육,P10601,태권도/무술학원,P85611,태권도 및 무술 교육기관,11,서울특별시,11350,노원구,11350619,중계본동,1135010600,중계동,1135010600103640019,1,대지,364,19.0,서울특별시 노원구 중계동 364-19,113503110009,서울특별시 노원구 한글비석로,242.0,NaN,1135010600103640019010971,삼부프라자,서울특별시 노원구 한글비석로 242,139861,1734,NaN,NaN,NaN,127.076956,37.649226
3,MA0101202210A0093845,이상한스냅,NaN,M1,과학·기술,M113,사진 촬영,M11301,사진촬영업,M73303,사진 처리업,11,서울특별시,11470,양천구,11470600,신월5동,1147010300,신월동,1147010300100090004,1,대지,9,4.0,서울특별시 양천구 신월동 9-4,114703005067,서울특별시 양천구 월정로,283.0,NaN,1147010300100090004000001,백송주택,서울특별시 양천구 월정로 283,158822,7902,NaN,NaN,NaN,126.828832,37.542117
4,MA010120220805430767,토끼정,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,한식 일반 음식점업,11,서울특별시,11500,강서구,11500603,가양1동,1150010500,마곡동,1150010500107740012,1,대지,774,12.0,서울특별시 강서구 마곡동 774-12,115003155046,서울특별시 강서구 마곡동로,55.0,NaN,1150010500107740012000001,마커스빌딩,서울특별시 강서구 마곡동로 55,157805,7802,NaN,2,NaN,126.833022,37.560053

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 473762 entries, 0 to 473761
Data columns (total 39 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     473762 non-null  object
 1   상호명        473762 non-null  object
 2   지점명        3962 non-null    object
 3   상권업종대분류코드  473762 non-null  object
 4   상권업종대분류명   473762 non-null  object
 5   상권업종중분류코드  473762 non-null  object
 6   상권업종중분류명   473762 non-null  object
 7   상권업종소분류코드  473762 non-null  object
 8   상권업종소분류명   473762 non-null  object
 9   표준산업분류코드   473706 non-null  object
 10  표준산업분류명    473706 non-null  object
 11  시도코드       473762 non-null  int64
 12  시도명        473762 non-null  object
 13  시군구코드      473762 non-null  int64
 14  시군구명       473762 non-null  object
 15  행정동코드      473762 non-null  int64
 16  행정동명       473762 non-null  object
 17  법정동코드      473762 non-null  int64
 18  법정동명       473762 non-null  object
 19  지번코드       473762 non-null  int64
 20  대지구분코드     473762 non-null  int64
 21  대지구분명      473762 non-null  object
 22  지번본번지      473762 non-null  int64
 23  지번부번지      396255 non-null  float64
 24  지번주소       473762 non-null  object
 25  도로명코드      473762 non-null  int64
 26  도로명        473762 non-null  object
 27  건물본번지      473761 non-null  float64
 28  건물부번지      62026 non-null   float64
 29  건물관리번호     473758 non-null  object
 30  건물명        225024 non-null  object
 31  도로명주소      473762 non-null  object
 32  구우편번호      473762 non-null  int64
 33  신우편번호      473762 non-null  int64
 34  동정보        0 non-null       float64
 35  층정보        325455 non-null  object
 36  호정보        0 non-null       float64
 37  경도         473762 non-null  float64
 38  위도         473762 non-null  float64
dtypes: float64(7), int64(10), object(22)
memory usage: 141.0+ MB

## **[3] 카페별로 데이터를 전처리하고 EDA하기**

In [18]:
cafe = df.query('상권업종소분류명 == "카페"')

In [19]:
cafe.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
10,MA010120220805430763,카페숲,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11545,금천구,11545710,시흥5동,1154510300,시흥동,1154510300109290010,1,대지,929,10.0,서울특별시 금천구 시흥동 929-10,115454151305,서울특별시 금천구 시흥대로40길,129.0,NaN,1154510300109290010016890,NaN,서울특별시 금천구 시흥대로40길 129,153860,8647,NaN,1,NaN,126.909939,37.446689
33,MA010120220805432035,카페활력소,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11710,송파구,11710642,문정2동,1171010800,문정동,1171010800106510003,1,대지,651,3.0,서울특별시 송파구 문정동 651-3,117103350849,서울특별시 송파구 법원로,96.0,NaN,1171010800106510003000001,문정법조프라자,서울특별시 송파구 법원로 96,138888,5855,NaN,1,NaN,127.120954,37.484021
80,MA010120220805433645,매머드커피외대,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11230,동대문구,11230740,이문1동,1123011000,이문동,1123011000102640223,1,대지,264,223.0,서울특별시 동대문구 이문동 264-223,112304115508,서울특별시 동대문구 천장산로7길,16.0,NaN,1123011000102640223003312,NaN,서울특별시 동대문구 천장산로7길 16,130829,2449,NaN,1,NaN,127.056962,37.598493
82,MA010120220805433429,포르마레,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11740,강동구,11740640,성내1동,1174010800,성내동,1174010800105340007,1,대지,534,7.0,서울특별시 강동구 성내동 534-7,117404172175,서울특별시 강동구 성내로9길,35.0,NaN,1174010800105340007007273,써니빌딩,서울특별시 강동구 성내로9길 35,134850,5397,NaN,1,NaN,127.125070,37.530474
111,MA010120220805433241,하프카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11680,강남구,11680531,논현2동,1168010800,논현동,1168010800102410003,1,대지,241,3.0,서울특별시 강남구 논현동 241-3,116803122011,서울특별시 강남구 학동로,342.0,NaN,1168010800102410004000001,에스케이허브블루,서울특별시 강남구 학동로 342,135830,6099,NaN,NaN,NaN,127.040820,37.516746

In [20]:
ediya = cafe.loc[cafe['상호명'].str.contains('이디야'),]
ediya

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
205,MA010120220805434517,이디야까치산로점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11500,강서구,11500591,화곡6동,1150010300,화곡동,1150010300111670000,1,대지,1167,NaN,서울특별시 강서구 화곡동 1167,115003115003,서울특별시 강서구 까치산로,182.0,NaN,1150010300111280005000001,DK182,서울특별시 강서구 까치산로 182,157016,7655,NaN,NaN,NaN,126.853872,37.553302
337,MA010120220805441922,이디야커피청룡,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11620,관악구,11620595,청룡동,1162010100,봉천동,1162010100115620018,1,대지,1562,18.0,서울특별시 관악구 봉천동 1562-18,116203120008,서울특별시 관악구 쑥고개로,80.0,NaN,1162010100115620018000001,제이빌딩,서울특별시 관악구 쑥고개로 80,151841,8831,NaN,1,NaN,126.945252,37.479204
1589,MA010120220805478457,이디야뚝섬유원지역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11215,광진구,11215847,자양4동,1121510500,자양동,1121510500100650001,1,대지,65,1.0,서울특별시 광진구 자양동 65-1,112153104007,서울특별시 광진구 능동로,21.0,NaN,1121510500100650001015693,NaN,서울특별시 광진구 능동로 21,143845,5085,NaN,1,NaN,127.067228,37.533546
3281,MA010120220805528646,이디야화곡본동,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11500,강서구,11500590,화곡본동,1150010300,화곡동,1150010300100980083,1,대지,98,83.0,서울특별시 강서구 화곡동 98-83,115004145272,서울특별시 강서구 까치산로4길,11.0,NaN,1150010300100980083016834,NaN,서울특별시 강서구 까치산로4길 11,157871,7722,NaN,1,NaN,126.844242,37.542215
3488,MA010120220805533853,이디야커피하월곡동점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11290,성북구,11290725,월곡2동,1129013600,하월곡동,1129013600100670037,1,대지,67,37.0,서울특별시 성북구 하월곡동 67-37,112903005044,서울특별시 성북구 오패산로,16.0,NaN,1129013600100670037016430,구원빌딩,서울특별시 성북구 오패산로 16,136865,2751,NaN,1,NaN,127.037474,37.603643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468146,MA0101202303A0025753,이디야커피천호현대점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11740,강동구,11740610,천호2동,1174010900,천호동,1174010900104320002,1,대지,432,2.0,서울특별시 강동구 천호동 432-2,117403123023,서울특별시 강동구 올림픽로,665.0,NaN,1174010900104320005011749,대일빌딩,서울특별시 강동구 올림픽로 665,134874,5248,NaN,NaN,NaN,127.123862,37.540918
468729,MA0101202302A0040633,이디야고척스카이돔점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11530,구로구,11530720,고척1동,1153010600,고척동,1153010600100760160,1,대지,76,160.0,서울특별시 구로구 고척동 76-160,115303000028,서울특별시 구로구 경인로,397.0,NaN,1153010600100760160014468,골든타워빌딩,서울특별시 구로구 경인로 397,152826,8227,NaN,1,NaN,126.863860,37.497687
469195,MA0101202302A0050540,이디야커피,우면동점,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11650,서초구,11650651,양재1동,1165010300,우면동,1165010300100020008,1,대지,2,8.0,서울특별시 서초구 우면동 2-8,116503121009,서울특별시 서초구 바우뫼로,20.0,NaN,1165010300100020008005336,고호빌딩,서울특별시 서초구 바우뫼로 20,137886,6763,NaN,1,NaN,127.025274,37.469980
473103,MA0101202303A0078675,이디야강서교차로점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11500,강서구,11500520,등촌1동,1150010200,등촌동,1150010200106540044,1,대지,654,44.0,서울특별시 강서구 등촌동 654-44,115002005007,서울특별시 강서구 공항대로,437.0,NaN,1150010200106540044027152,주신기업,서울특별시 강서구 공항대로 437,157842,7571,NaN,1,NaN,126.855907,37.554943
473707,MA0101202303A0015918,이디야논현,학동점,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11680,강남구,11680521,논현1동,1168010800,논현동,1168010800100390020,1,대지,39,20.0,서울특별시 강남구 논현동 39-20,116804166129,서울특별시 강남구 논현로131길,28.0,NaN,1168010800100390020006783,NaN,서울특별시 강남구 논현로131길 28,135815,6045,NaN,1,NaN,127.028094,37.514074

In [21]:
twosome = cafe.loc[cafe['상호명'].str.contains('투썸플레이스'),]
twosome

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
2538,MA010120220805506409,투썸플레이스,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11560,영등포구,11560660,신길4동,1156013200,신길동,1156013200149020007,1,대지,4902,7.0,서울특별시 영등포구 신길동 4902-7,115603118014,서울특별시 영등포구 신길로,162.0,NaN,1156013200149020007000001,NaN,서울특별시 영등포구 신길로 162,150861,7362,NaN,2,NaN,126.911353,37.506649
5004,MA010120220805697985,투썸플레이스강동,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11740,강동구,11740600,천호1동,1174010900,천호동,1174010900100250002,1,대지,25,2.0,서울특별시 강동구 천호동 25-2,117402000006,서울특별시 강동구 양재대로,1615.0,NaN,1174010900100250002012281,NaN,서울특별시 강동구 양재대로 1615,134861,5306,NaN,2,NaN,127.143497,37.549676
6217,MA010120220805816209,투썸플레이스구로항동점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11530,구로구,11530800,항동,1153011200,항동,1153011200101210001,1,대지,121,1.0,서울특별시 구로구 항동 121-1,115303000020,서울특별시 구로구 서해안로,2096.0,NaN,1153011200101210001000001,NaN,서울특별시 구로구 서해안로 2096,152140,8368,NaN,NaN,NaN,126.822875,37.479751
7016,MA010120220805906456,투썸플레이스문정KD70점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11710,송파구,11710642,문정2동,1171010800,문정동,1171010800106400008,1,대지,640,8.0,서울특별시 송파구 문정동 640-8,117104853410,서울특별시 송파구 정의로8길,4.0,NaN,1171010800100000000000007,KD70,서울특별시 송파구 정의로8길 4,138888,5836,NaN,1,NaN,127.115688,37.485694
7414,MA010120220805927117,투썸플레이스수락산역점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11350,노원구,11350630,상계1동,1135010500,상계동,1135010500111320063,1,대지,1132,63.0,서울특별시 노원구 상계동 1132-63,113504130252,서울특별시 노원구 동일로243길,13.0,NaN,1135010500111320071009682,대성빌딩,서울특별시 노원구 동일로243길 13,139838,1607,NaN,1,NaN,127.054366,37.678205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468318,MA0101202303A0035651,투썸플레이스역삼,자이점,I2,음식,I212,비알코올,I21201,카페,NaN,NaN,11,서울특별시,11680,강남구,11680650,역삼2동,1168010100,역삼동,1168010100107210039,1,대지,721,39.0,서울특별시 강남구 역삼동 721-39,116803005086,서울특별시 강남구 언주로,419.0,NaN,1168010100107210039023667,행남자기,서울특별시 강남구 언주로 419,135920,6222,NaN,1,NaN,127.043451,37.500269
471047,MA0101202302A0106558,투썸플레이스용산트윈시티점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11170,용산구,11170530,남영동,1117010700,동자동,1117010700100560000,1,대지,56,NaN,서울특별시 용산구 동자동 56,111702005005,서울특별시 용산구 한강대로,366.0,NaN,1117010700100370085000001,트윈시티남산,서울특별시 용산구 한강대로 366,140160,4323,NaN,1,NaN,126.972895,37.551081
472359,MA0101202303A0039987,투썸플레이스신촌대로점,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11440,마포구,11440660,서교동,1144011000,노고산동,1144011000100490025,1,대지,49,25.0,서울특별시 마포구 노고산동 49-25,114403005057,서울특별시 마포구 신촌로,74.0,NaN,1144011000100490025029068,NaN,서울특별시 마포구 신촌로 74,121807,4057,NaN,2,NaN,126.933986,37.555845
472478,MA0101202303A0023543,투썸플레이스대림,삼거리점,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11560,영등포구,11560700,대림1동,1156013300,대림동,1156013300109520019,1,대지,952,19.0,서울특별시 영등포구 대림동 952-19,115602005010,서울특별시 영등포구 시흥대로,675.0,NaN,1156013300109520019005509,삼성YJ그랜드빌딩,서울특별시 영등포구 시흥대로 675,150951,7442,NaN,1,NaN,126.908433,37.492025
472712,MA0101202303A0048626,투썸플레이스사당역,로데오점,I2,음식,I212,비알코올,I21201,카페,I56221,커피 전문점,11,서울특별시,11650,서초구,11650610,방배2동,1165010100,방배동,1165010100104500025,1,대지,450,25.0,서울특별시 서초구 방배동 450-25,116504163157,서울특별시 서초구 방배천로2길,5.0,NaN,1165010100104500025013409,성지빌딩,서울특별시 서초구 방배천로2길 5,137818,6693,NaN,1,NaN,126.983144,37.477194

In [25]:
ediya_count = ediya.groupby('시군구명').size().to_frame().reset_index().rename({0:'count'}, axis=1).sort_values('count', ascending=False)
ediya_count

    시군구명  count
19  영등포구     38
17   송파구     35
0    강남구     33
12   마포구     30
3    강서구     29
16   성북구     29
22   종로구     29
23    중구     28
6    구로구     28
4    관악구     26
24   중랑구     25
21   은평구     24
14   서초구     24
8    노원구     23
10  동대문구     23
18   양천구     23
5    광진구     22
1    강동구     22
9    도봉구     22
11   동작구     21
7    금천구     19
15   성동구     18
2    강북구     17
13  서대문구     17
20   용산구     13

In [26]:
twosome_count = twosome.groupby('시군구명').size().to_frame().reset_index().rename({0:'count'}, axis=1).sort_values('count', ascending=False)
twosome_count

    시군구명  count
0    강남구     37
23    중구     30
17   송파구     26
14   서초구     24
12   마포구     23
3    강서구     16
19  영등포구     14
15   성동구     12
1    강동구     10
6    구로구     10
7    금천구     10
22   종로구     10
13  서대문구     10
16   성북구      9
5    광진구      9
8    노원구      9
4    관악구      8
18   양천구      8
24   중랑구      8
2    강북구      6
10  동대문구      6
9    도봉구      5
20   용산구      4
21   은평구      4
11   동작구      3

In [27]:
import plotly.express as px

fig = px.bar(data_frame=ediya_count, x='시군구명', y='count', color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white', text_auto=True, title='서울시 구별 이디야 점포수')
fig.show()

In [28]:
fig = px.bar(data_frame=twosome_count, x='시군구명', y='count', color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white', text_auto=True, title='서울시 구별 투썸플레이스 점포수')
fig.show()

## **[4] folium으로 지도에 시각화하기**

In [29]:
f = folium.Figure(width=700, height=500)
m = folium.Map(location=[37.566535, 126.9779692], zoom_start=11).add_to(f)
m

In [30]:
folium.Choropleth(geo_data = geo_json, fill_color = 'gray').add_to(m)
m

In [31]:
f = folium.Figure(width=700, height=500)
m = folium.Map(location=[37.566535, 126.9779692], zoom_start=11).add_to(f)
folium.Choropleth(geo_data = geo_json
                  , data=ediya_count
                  , columns=['시군구명', 'count']
                  , key_on='properties.name'
                  , fill_color = 'YlGn'
                  , fill_opacity = 0.7
                  , line_opacity = 0.7
                  , legend_name = '서울시 구별 이디야 매장수').add_to(m)
m

In [32]:
f = folium.Figure(width=700, height=500)
m = folium.Map(location=[37.566535, 126.9779692], zoom_start=11).add_to(f)
folium.Choropleth(geo_data = geo_json
                  , data=twosome_count
                  , columns=['시군구명', 'count']
                  , key_on='properties.name'
                  , fill_color = 'BuPu'
                  , fill_opacity = 0.7
                  , line_opacity = 0.7
                  , legend_name = '서울시 구별 투썸플레이스 매장수').add_to(m)
m

In [33]:
ediya_twosome = ediya_count.merge(twosome_count, on='시군구명', suffixes=('_이디야','_투썸'))
ediya_twosome['이디야_ratio'] = ediya_twosome['count_이디야'] / ediya_twosome['count_이디야'].sum()
ediya_twosome['투썸_ratio'] = ediya_twosome['count_투썸'] / ediya_twosome['count_투썸'].sum()
ediya_twosome['투썸 상대적 비율'] = ediya_twosome['투썸_ratio'] / ediya_twosome['이디야_ratio']

In [34]:
ediya_twosome

    시군구명  count_이디야  count_투썸  이디야_ratio  투썸_ratio  투썸 상대적 비율
0   영등포구         38        14   0.061489  0.045016   0.732104
1    송파구         35        26   0.056634  0.083601   1.476160
2    강남구         33        37   0.053398  0.118971   2.228004
3    마포구         30        23   0.048544  0.073955   1.523473
4    강서구         29        16   0.046926  0.051447   1.096352
5    성북구         29         9   0.046926  0.028939   0.616698
6    종로구         29        10   0.046926  0.032154   0.685220
7     중구         28        30   0.045307  0.096463   2.129077
8    구로구         28        10   0.045307  0.032154   0.709692
9    관악구         26         8   0.042071  0.025723   0.611427
10   중랑구         25         8   0.040453  0.025723   0.635884
11   은평구         24         4   0.038835  0.012862   0.331190
12   서초구         24        24   0.038835  0.077170   1.987138
13   노원구         23         9   0.037217  0.028939   0.777576
14  동대문구         23         6   0.037217  0.019293   0.518384
15   양천구         23         8   0.037217  0.025723   0.691179
16   광진구         22         9   0.035599  0.028939   0.812920
17   강동구         22        10   0.035599  0.032154   0.903245
18   도봉구         22         5   0.035599  0.016077   0.451622
19   동작구         21         3   0.033981  0.009646   0.283877
20   금천구         19        10   0.030744  0.032154   1.045862
21   성동구         18        12   0.029126  0.038585   1.324759
22   강북구         17         6   0.027508  0.019293   0.701343
23  서대문구         17        10   0.027508  0.032154   1.168905
24   용산구         13         4   0.021036  0.012862   0.611427

In [35]:
f = folium.Figure(width=700, height=500)
m = folium.Map(location=[37.566535, 126.9779692], zoom_start=11).add_to(f)
folium.Choropleth(geo_data = geo_json
                  , data=ediya_twosome
                  , columns=['시군구명', '투썸 상대적 비율']
                  , key_on='properties.name'
                  , fill_color = 'RdPu'
                  , fill_opacity = 0.7
                  , line_opacity = 0.7
                  , legend_name = '서울시 구별 투썸 상대적 비율').add_to(m)
m

In [36]:
ediya_df = ediya[['상호명','경도','위도']].copy()
ediya_df['kind'] = '이디야'

twosome_df = twosome[['상호명','경도','위도']].copy()
twosome_df['kind'] = '투썸'

dff = pd.concat([ediya_df, twosome_df])
dff.head()

             상호명          경도         위도 kind
205     이디야까치산로점  126.853872  37.553302  이디야
337      이디야커피청룡  126.945252  37.479204  이디야
1589  이디야뚝섬유원지역점  127.067228  37.533546  이디야
3281     이디야화곡본동  126.844242  37.542215  이디야
3488  이디야커피하월곡동점  127.037474  37.603643  이디야

In [37]:
dff.tail()

                  상호명          경도         위도 kind
468318       투썸플레이스역삼  127.043451  37.500269   투썸
471047  투썸플레이스용산트윈시티점  126.972895  37.551081   투썸
472359    투썸플레이스신촌대로점  126.933986  37.555845   투썸
472478       투썸플레이스대림  126.908433  37.492025   투썸
472712      투썸플레이스사당역  126.983144  37.477194   투썸

In [38]:
from _plotly_utils.basevalidators import TitleValidator
f = folium.Figure(width=700, height=500)
m = folium.Map(location=[37.566535, 126.9779692], zoom_start=11).add_to(f)

for idx in dff.index:
    lat = dff.loc[idx, '위도']
    long = dff.loc[idx, '경도']
    title = dff.loc[idx, '상호명']

    if dff.loc[idx, 'kind'] == "이디야":
        color = '#1d326c'
    else:
        color = '#D70035'
    folium.CircleMarker([lat, long]
                        , radius=3
                        , color = color
                        , tooltip = title).add_to(m)

m