# **plotly로 유형별 그래프 그리기**

## **[1] 산점도**


```
px.scatter(data_frame=데이터, x=X축 컬럼, y=Y축 컬럼, color=색, trendline='ols') #trendline은 추세선 추가
```

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
penguins = sns.load_dataset('penguins')

In [3]:
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [4]:
fig = px.scatter(data_frame=penguins, x='bill_length_mm', y='bill_depth_mm'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [5]:
fig = px.scatter(data_frame=penguins, x='bill_length_mm', y='bill_depth_mm', color='sex'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [7]:
fig = px.scatter(data_frame=penguins, x='bill_length_mm', y='bill_depth_mm', color='island', symbol='sex'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

## seaborn에서는 모양을 다르게 하려면 style을 사용했었지만,
## plotly에서는 symbol을 사용한다.

In [ ]:
fig = px.scatter(data_frame=penguins, x='bill_length_mm', y='bill_depth_mm', color='sex', facet_col='island'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()
## facet_row와 facet_col을 사용하면 여러 개의 subplot을 만들 수 있다.
## facet_row는 행으로 나누고, facet_col은 열로 나눈다.

In [10]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.4-cp313-cp313-win_amd64.whl.metadata (9.5 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\ryang\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.4)
Collecting scipy!=1.9.2,>=1.8 (from statsmodels)
  Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\ryang\appdata\local\programs\python\python313\lib\site-packages (from statsmodels) (2.2.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\ryang\appdata\roaming\python\python313\site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ryang\appdata\roaming\python\python313\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ryang\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ryang\appdata\local\programs\python\python313\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ryang\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.4-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------------------------- -------------- 6.3/9.8 MB 32.2 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 33.2 MB/s eta 0:00:00
Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl (41.0 MB)
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   ----- ---------------------------------- 6.0/41.0 MB 29.9 MB/s eta 0:00:02
   ------------------ --------------------- 18.9/41.0 MB 45.5 MB/s eta 0:00:01
   ----------------------------- ---------- 30.4/41.0 MB 49.4 MB/s eta 0:00:01
   ------------------------------ --------- 30.9/41.0 MB 37.9 MB/s eta 0:00:01
   -------------------------------------- - 39.1/41.0 MB 37.2 MB/s eta 0:00:01
   ---------------------------------------- 41.0/41.0 MB 33.8 MB/s eta 0:00:00
Installing collected packages: scipy, patsy, statsmodels
Successfully installed patsy-1.0.1 scipy-1.15.2 statsmodels-0.14.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
fig = px.scatter(data_frame=penguins, x='bill_length_mm', y='bill_depth_mm', trendline='ols'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [12]:
fig = px.scatter(data_frame=penguins, x='bill_length_mm', y='bill_depth_mm', color='sex', facet_col='island', trendline='ols'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

## **[2] 분포 살펴보기**


```
px.histogram(data_frame=데이터, x=X축 컬럼, color=색) #히스토그램
px.box(data_frame=데이터, x=X축 컬럼, y=Y축 컬럼, color=색) #상자그림
plotly에서는 밀도 함수는 그릴 수 없다.
```

### **히스토그램**

In [13]:
fig = px.histogram(data_frame=penguins, x='flipper_length_mm', color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

## **상자그림**

In [14]:
fig = px.box(data_frame=penguins, x='body_mass_g', color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [15]:
fig = px.box(data_frame=penguins, x='body_mass_g', y='species', color='sex'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

## **[3] 막대 그래프**


```
px.bar(data_frame=데이터, x=X축 컬럼, y=Y축 컬럼, color=색, barmode='group') #누적으로 쌓아서 올리지 않으려면 barmode = 'group'을 추가한다
plotly에서는 seaborn에서 있었던 카운트플랏은 없다. 
count하고 싶으면 groupby로 카운트를 하고 그 데이터로 그려준다.
```
df.groupby('열이름')         # 그룹화만 함  
df.groupby('열이름').mean()  # 그룹별 평균  
df.groupby('열이름').sum()   # 그룹별 합계  
df.groupby('열이름').count() # 그룹별 개수

In [30]:
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [41]:
titanic_groupby = titanic.groupby(['sex','class'])[['survived']].mean().reset_index()
titanic_groupby
## reset_index()는 groupby 결과의 인덱스를 다시 숫자인덱스로 바꾼다.
## groupby(['sex','class'])는 그룹화 기준인 'sex'와 'class'를 인덱스로 만들어서 multiple index를 만든다.
## 이렇게되면 후속작업에서 불편할수 있어서 sex와 clss를 일반열(columns)로 내려와서 dataframe이 평평해진다.

C:\Users\ryang\AppData\Local\Temp\ipykernel_12632\845878409.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

      sex   class  survived
0  female   First  0.968085
1  female  Second  0.921053
2  female   Third  0.500000
3    male   First  0.368852
4    male  Second  0.157407
5    male   Third  0.135447

In [38]:
fig = px.bar(data_frame=titanic_groupby, x='class', y='survived', color='sex'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [39]:
fig = px.bar(data_frame=titanic_groupby, x='class', y='survived', color='sex', barmode='group'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [34]:
fig = px.bar(data_frame=titanic_groupby, x='class', y='survived', color='sex', barmode='group', text_auto='.2f'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [35]:
titanic_groupby1 = titanic.groupby(['sex','class','alone'])[['survived']].mean().reset_index()
titanic_groupby1

C:\Users\ryang\AppData\Local\Temp\ipykernel_12632\381244162.py:1: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

       sex   class  alone  survived
0   female   First  False  0.966667
1   female   First   True  0.970588
2   female  Second  False  0.931818
3   female  Second   True  0.906250
4   female   Third  False  0.416667
5   female   Third   True  0.616667
6     male   First  False  0.425532
7     male   First   True  0.333333
8     male  Second  False  0.277778
9     male  Second   True  0.097222
10    male   Third  False  0.180723
11    male   Third   True  0.121212

In [36]:
fig = px.bar(data_frame=titanic_groupby1, x='class', y='survived', color='sex', facet_col='alone', barmode='group', text_auto='.2f'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

## **[4] 선그래프**


```
px.line(data_frame=데이터, x=X축 컬럼, y=Y축 컬럼, color=색)
```

In [42]:
flights = sns.load_dataset("flights")
flights

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [43]:
may_flights = flights.query('month == "May"')
fig = px.line(data_frame=may_flights, x="year", y="passengers"
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

In [44]:
fig = px.line(data_frame=flights, x="year", y="passengers", color='month'
, color_discrete_sequence=px.colors.qualitative.Set2, template='plotly_white')
fig.show()

## **[5] 히트맵**


```
px.imshow(데이터, text_auto=텍스트포맷, color_continuous_scale=컬러맵)
```

In [47]:
titanic_corr = titanic[['survived','age','fare','sibsp','pclass']].corr()
titanic_corr

          survived       age      fare     sibsp    pclass
survived  1.000000 -0.077221  0.257307 -0.035322 -0.338481
age      -0.077221  1.000000  0.096067 -0.308247 -0.369226
fare      0.257307  0.096067  1.000000  0.159651 -0.549500
sibsp    -0.035322 -0.308247  0.159651  1.000000  0.083081
pclass   -0.338481 -0.369226 -0.549500  0.083081  1.000000

In [48]:
fig = px.imshow(titanic_corr, text_auto='.2f', color_continuous_scale='YlOrBr')
fig.show()

In [49]:
titanic_pivot = pd.pivot_table(data=titanic, index='sex', columns='class', values='survived', aggfunc='mean')
titanic_pivot

C:\Users\ryang\AppData\Local\Temp\ipykernel_12632\31230025.py:1: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [50]:
fig = px.imshow(titanic_pivot, text_auto='.2f', color_continuous_scale='Purples')
fig.show()

## **[6] 파이차트**


```
px.pie(data_frame=데이터, values=값, names=라벨)
seaborn에서는 없지만 plotly에서는 존재재
```

In [45]:
df = px.data.tips()
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [46]:
fig = px.pie(df, values='tip', names='day', color_discrete_sequence=px.colors.qualitative.Pastel)
fig.show()

In [51]:
df.groupby('day')[['tip']].sum()

         tip
day
Fri    51.96
Sat   260.40
Sun   247.39
Thur  171.83